version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongodb_container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=abdel
      - MONGO_INITDB_ROOT_PASSWORD=abdel@12
      - MONGO_INITDB_DATABASE=bookTrackerDB
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: mongod --auth

volumes:
  mongo_data:
    driver: local